print("'My name is Simon'.split()")
print('My name is Simon'.split())
print("'MyABCnameABCisABCSimon'.split('ABC')")
print('MyABCnameABCisABCSimon'.split('ABC'))
print("'My name is Simon'.split('m')")
print('My name is Simon'.split('m'))
